### ISSUE TITLE
20磅行距问题

### ISSUE THREAD

**Issue by YifanRuan** [singularity-s0/fducs2024-thesis-template#2]
现在的行距设置似乎是有问题的？如果我调整 baselineskip, 实际上行距不会有变化。

我现在的方案是使用 zhlineskip 并把倍数设置成字体高度的 1.67 倍。要求 20 磅的地方都是小四字体，高度 12 磅，因此 1.67 倍就是 20 磅。

代码如下

```tex
% \setlength{\baselineskip}{20pt}
\usepackage[bodytextleadingratio=1.67]{zhlineskip}
```

这样改了以后看起来有点区别，但是不大。

**Comment by singularity-s0** [comment]
可以这样改，提交PR吧
