### ISSUE TITLE
参考文献标注问题

### ISSUE THREAD

**Issue by YifanRuan** [singularity-s0/fducs2024-thesis-template#7]
请问要求中是否规定参考文献的文中标注要和正文大小一样。我查到的 GB/T 7714 要求是用上标。

**Comment by singularity-s0** [comment]
@w568w 看一下？

**Comment by w568w** [comment]
1. 《1116 计算机学院、软件学院本科毕业论文撰写规范》中没有注明是否需要上标，甚至没有提到 GB/T 7714-2015；
2. 《1116 计算机学院、软件学院本科毕业论文样稿》中规定**参考文献表**需「严格遵循 GB/T 7714-2015 要求」，但未对文中引用格式指明要求；
3. GB/T 7714-2015 中，文字说明仅要求「用方括号标注」，但给出的示例均为上标；
4. `GB` 后的 `/T` 代表这一标准为推荐规范而非强制规范；
5. 实际的知网学位论文中，两者（上标/正文）皆有，如下两图。因此，我认为这一规定没有明确规范，或是各个学校要求不同；
6. 我没有听到过因不用上标方式引用而出问题的事例。你可以咨询前届学长。

---

正文（某博士学位论文）：

![图片](https://github.com/singularity-s0/fducs2024-thesis-template/assets/8389787/7be11e16-388b-4d36-859e-69994a1cc4a9)

上标（某硕士学位论文）：

![图片](https://github.com/singularity-s0/fducs2024-thesis-template/assets/8389787/478e04a3-9fa3-4179-8d54-0273e962f188)

**Comment by YifanRuan** [comment]
了解了。那这个部分留着自己改吧，我把这个 issue 关掉了。
